### ISSUE TITLE
[Feat] Firebase와 통신하는 API를 구현합니다.

### ISSUE THREAD

**Issue by skycat0212** [DeveloperAcademy-POSTECH/MacC-GetARock#119]
## 💡 Issue

Firebase와 통신하는 API를 구현합니다.

## 📝  todo
User
- [x] Firebase에 활용할 User Model 확립
- [x] 테스트 계정 등록
- [x] 로그인 API 구현

모여락 API
- [x] 모여락 조회
- [x] 모여락 등록
- [ ] 모여락 삭제
- [x] 댓글 조회
- [x] 댓글 등록
- [ ] 댓글 삭제

방명록
- [x] 방명록 조회
- [x] 방명록 등록
- [ ] 방명록 삭제
