### ISSUE TITLE
[Feat] (스누피 데모 팔로업) 모여락 페이지를 데이터와 동적으로 연결시기 위한 작업입니다.

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MacC-GetARock#125]
## 💡 Issue

현재 develop 브랜치의 모여락 정보 페이지의 코드 수준이 데이터와 동적으로 작동하지 않게 구현되어있어서, snoopy-demo 수준의 데이터와  상호작용을 위해서 코드를 추가합니다. 

## 📝  todo
- [ ] todo !
- [ ] CommentView와 연결했을때 높이 고정설정
- [ ] 동적인 데이터 변화를 위한 Outlet 연결
- [ ] 모집중 상태에 따른 상태 변경 추가
- [ ] 전체적인 코드 정리
