### ISSUE TITLE
[Design] 티켓모양 레이아웃을 구현하려고 합니다.

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MacC-GetARock#20]
## 💡 Issue

상세 프로필과 프로필 카드에 사용될 티켓모양 레이아웃을 구현합니다. 
어떻게 해야할지 감이 잡히지 않아서 우선은 이것저것 시도해 보려고 합니다.
## 📝  todo
- [x] 어떤식으로 컴포넌트 화 할지 먼저 구상해보기
- [x] 설계 짜기 
- [ ] xib 사용방법 공부
- [ ] stackView의 부분적인 호출 방법 고찰
