### ISSUE TITLE
[Feat] 선택창 버튼의 UI를 구현합니다.

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/MacC-GetARock#21]
## 💡 Issue

개인/밴드, 포지션, 장르 선택에 쓰이는 버튼의 UI를 구현합니다.

## 📝  todo
- [ ] 개인/밴드 선택 버튼 구현
- [ ] 포지션 선택 버튼 구현
- [ ] 장르 선택 버튼 구현

**Comment by compuTasha** [comment]
Pivot 으로 인해 백로그 전체가 변경되었습니다.
