### ISSUE TITLE
[Design] 유효성 검사가 가능한 텍스트뷰 UI를 구현합니다. 

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MacC-GetARock#24]
## 💡 Issue

재사용을 고려하여 아래와 같은 텍스트뷰 UI를 구현합니다. 
<img src="https://user-images.githubusercontent.com/18394923/199658371-dae59249-287d-4914-9818-3e1c4658ab65.png" width="30%" height="30%">
<img src="https://user-images.githubusercontent.com/18394923/199658405-69529d19-bd1c-46c3-a8aa-7245744cc603.png" width="30%" height="30%">

## 📝  todo

- [ ] 텍스트뷰 커스터마이징
  - [ ] 모양, 배경색, 테두리, 선택중일 때의 테두리
    - [ ] 배경색이 다른 경우(프로필 확인) 있으므로 배경색 지정 가능하도록 조정
  - [ ] 플레이스홀더
- [ ] 유효성 검사
  - [ ] 유효성 검사 함수
  - [ ] 미통과시 조건에 맞는 스트링 출력

**Comment by compuTasha** [comment]
Pivot 으로 인해 백로그 전체가 변경되었습니다.
