### ISSUE TITLE
[Design] "내 모여락" 탭을 눌렀을 때 나오는 리스트 화면 UI를 구현합니다.

### ISSUE THREAD

**Issue by taehyeonk** [DeveloperAcademy-POSTECH/MacC-GetARock#30]
## 💡 Issue

"내 모여락" 버튼을 눌렀을 때 나오는 모달 안에 들어갈 UI View를 구현합니다.
<img src="https://user-images.githubusercontent.com/29690062/202830431-2615dc7a-efb3-4b26-8f13-77161862f6ac.png" width="30%" height="30%">

## 📝  todo

- [ ] collectionview 사용해서 목록 만들어 보기
- [ ] tableview 사용해서 목록 만들어 보기
- [ ] 각각의 항목에 들어갈 요소 구현 (이벤트 제목, 시간, 상태)
