### ISSUE TITLE
[Design] 주변의 이벤트와 밴드 정보를 확인할 수 있는 지도 뷰 UI를 구성합니다. 

### ISSUE THREAD

**Issue by compuTasha** [DeveloperAcademy-POSTECH/MacC-GetARock#31]
## 💡 Issue
첫 화면이 되는 맵 뷰의 UI를 구성합니다. 
1차 스프린트에서는 디자인을 반영하지 않고
최대한 기본 컴포넌트를 활용해서 구현하기로 결정되었습니다.

<img src="https://user-images.githubusercontent.com/51108729/202397002-536d3d62-387d-49d9-b566-73b02bc24baa.png" width="30%" height="30%"> 

## 📝  todo
- [x] 지도 뷰 구현 - mapkit
- [x] '설정' 버튼 UI 구현
- [x] '현 위치' 버튼 UI 구현
- [x] '모여락 열기' 버튼 UI 구현
- [x] '내 활동' 버튼 UI 구현
- [x] '마이 페이지' 버튼 UI 구현

<br>
