### ISSUE TITLE
[Design] 밴드정보의 방명록 페이지의 UI를 구성합니다. 

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MacC-GetARock#32]
## 💡 Issue

방명록 탭 아래에 있는 뷰를 구현합니다. 분기처리는 후순위로 미루고 모든 요소가 들어간 UI 구성부터 디자인 하려고 합니다.

StackView 안에 CollectionView로 방명록 히스토리를 구현하고, UIview에 방명록 남기기 버튼을 구현할 예정입니다.

<img width="281" alt="스크린샷 2022-11-17 오후 6 05 01" src="https://user-images.githubusercontent.com/101700487/202403125-c85d3de9-deb6-4adc-bc3b-dd625a328640.png">

## 📝  todo
우선순위
- [ ] 스토리보드로 방명록 구현하기
- [ ] 동작 확인을 위한 더미데이터 넣기 

후순위
- [ ] 방명록 남기기 버튼 구현
- [ ] 방명록 남기기 버튼을 통해 방명록 작성 창으로 넘어가기
- [ ] 남긴 방명록을 방명록에 추가하기
- [ ] 방명록의 햄버거 버튼을 클릭했을때 신고하기와 삭제하기 가 들어간 액션시트 구현하기
- [ ] 방명록의 햄버거 버튼을 클릭하여 삭제하기 기능 구현하기
- [ ] 방명록의 햄버거 버튼을 클릭하여 신고하기 기능 구현하기
- [ ] 신고하기 페이지 만들기

**Comment by siro96-01** [comment]
노엘과의 테스크 교환으로 인해서 이슈를 close 합니다...ㅠㅠ 잘가 내친구...ㅠ
