### ISSUE TITLE
[Design] 모여락(밴드 이벤트) 입력 화면의 UI를 구성합니다. 

### ISSUE THREAD

**Issue by EuniceNam** [DeveloperAcademy-POSTECH/MacC-GetARock#36]
## 💡 Issue

모여락(밴드 이벤트) 입력 화면의 UI를 구성합니다. 
색은 사용하며, 기본 컴포넌트로 구성합니다. 
모여락의 장소 입력 스크린 연결과 상단 UI를 위해 네비게이션 컨트롤을 추가합니다. 

<img src="https://user-images.githubusercontent.com/18394923/202601867-d6e25f74-19b1-4f52-a4d0-86c3f6b7f8d2.png" width="30%" height="30%"> 

## 📝  todo
- [x] 구분선, 취소 버튼, 완료 버튼
- [x] 제목(UITextField), 주최(UILabel), 시간(UIDatePicker), 소개(UITextView)
- [x] 네비게이션컨트롤 추가, 네비게이션바 커스텀 
(위치는 다른 화면으로 이동하므로 다른 이슈로 분리합니다)
