### ISSUE TITLE
[Design] 모여락(이밴트)의 정보 화면의 UI 를 구성합니다.

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MacC-GetARock#37]
## 💡 Issue

모여락(이밴트)의 정보 화면의 UI를 구현합니다.  댓글달기 부분부터는 노엘의 파트와 겹치기 때문에 우선은 모여락을 연 밴드의 정보와 날짜 위치에 관한 label 을 만들고, 소개글은 자유 텍스트로 다이나믹하게 사이즈를 변경시킬 예정입니다. 
StackView를 사용하여 구현할 예정입니다. 최종적으로는 댓글달기 버튼과 그 밑의 화면도 함께 구현해야하는 페이지이기 때문에, 구현할때 댓글View를 넣을 수 있는 빈 View를 만들어 놓을 예정입니다.
<img width="267" alt="스크린샷 2022-11-18 오후 3 25 11" src="https://user-images.githubusercontent.com/101700487/202635405-d49df921-5a7b-4baf-aff8-df5e192dda70.png">

## 📝  todo

- [x] 모여락(이밴트) 이름 UILabel 생성
- [x] 모여락(이밴트)의 밴드명 UILabel 생성
- [x] 모여락 시작 시간 UILabel 생성
- [x] 중간에 구분선을 위한 View 생성
- [x] 모여락 소개 Text 노출
- [x] 뷰 확인을 위한 더미 데이터와 더미 모델 생성
- [ ] 메인 더미 데이터와 뷰 연결

**Comment by siro96-01** [comment]
스누피가 만들어준 모델과 더미 데이터를 뷰에 연결하기 위해서 다시 issue 를 열었습니다.
