### ISSUE TITLE
[Add] 더미 데이터 생성

### ISSUE THREAD

**Issue by skycat0212** [DeveloperAcademy-POSTECH/MacC-GetARock#50]
## 💡 Issue

밴드 / 모임 / 댓글 / 방명록 에 대한 더미 데이터를 만듭니다.

## 📝  todo
- [ ] 밴드 더미데이터 만들기
- [ ] 모임 더미데이터 만들기
- [ ] 댓글 더미데이터 만들기
- [ ] 방명록 더미데이터 만들기
