### ISSUE TITLE
[Feat] 신고 / 삭제를 위한 기능을 구현합니다. 

### ISSUE THREAD

**Issue by siro96-01** [DeveloperAcademy-POSTECH/MacC-GetARock#68]
## 💡 Issue

모여락 혹은 방명록에 관한 신고, 삭제 기능을 구현합니다.  분기 처리를 통해서 삭제는 작성자만 가능하도록 해야하지만, 우선 분기처리는 후순위로 두고 개발 하도록 하겠습니다. 신고 페이지의 양식은 기존에 사용되고 있는 신고 UX를 따라가려고 합니다.  

신고 사유 페이지는 인스타그램 신고페이지를 참고해서 임의로 디자인 했습니다.  
신고/ 삭제버튼을 클릭했을때 한번 더 재고하는 알랏 창을 띄웁니다. 

ellipsis를 클릭했을때 뜨는 액션시트는 UIAlertController를 사용하여 구현 할 예정입니다. 
신고 사유 페이지는 TableView에 Header를 삽입하여 구현할 예정입니다. 

<img width="200" alt="스크린샷 2022-11-21 오후 8 32 54" src="https://user-images.githubusercontent.com/101700487/203040784-5b5393c9-810b-4d45-8b58-7c1707f42ec6.png">
<img width="200" alt="스크린샷 2022-11-21 오후 8 32 36" src="https://user-images.githubusercontent.com/101700487/203040811-057ce151-1607-485d-a4b0-945be1339192.png">
<img width="200" alt="스크린샷 2022-11-21 오후 8 33 02" src="https://user-images.githubusercontent.com/101700487/203043594-15526aab-30e3-47b6-a977-8e3747b7adb8.png">

## 📝  todo
- [ ] ellipsis 버튼 선택시 삭제/ 신고 버튼이 있는 actionSheet 노출
- [ ] 액션시트의 '신고' 선택시, 신고하기 양식 노출
- [ ] 신고하기 양식에서 항목 선택시 재고를 위한 신고하기 alert 노출
- [ ] 액션시트의 '삭제' 선택시, 댓글이나 모여락을 삭제할 수 있음
- [ ] 분기 처리를 통한 신고 / 삭제 버튼 나누기

**Comment by siro96-01** [comment]
혹시 깃헙 이슈에서  이미지 가로로 한줄에 보이게 하는법 아시나요...ㅋㅋㅋ

**Comment by compuTasha** [comment]
> 혹시 깃헙 이슈에서 이미지 가로로 한줄에 보이게 하는법 아시나요...ㅋㅋㅋ

마크다운 테이블에 넣어서 한 줄로 정렬할 수 있어요!!

| <img width="200" alt="스크린샷 2022-11-21 오후 8 32 54" src="https://user-images.githubusercontent.com/101700487/203040784-5b5393c9-810b-4d45-8b58-7c1707f42ec6.png"> | <img width="200" alt="스크린샷 2022-11-21 오후 8 32 36" src="https://user-images.githubusercontent.com/101700487/203040811-057ce151-1607-485d-a4b0-945be1339192.png"> | <img width="200" alt="스크린샷 2022-11-21 오후 8 33 02" src="https://user-images.githubusercontent.com/101700487/203043594-15526aab-30e3-47b6-a977-8e3747b7adb8.png"> |
|:---:|:---:|:---:|

```
| <img width="200" alt="스크린샷 2022-11-21 오후 8 32 54" src="https://user-images.githubusercontent.com/101700487/203040784-5b5393c9-810b-4d45-8b58-7c1707f42ec6.png"> | <img width="200" alt="스크린샷 2022-11-21 오후 8 32 36" src="https://user-images.githubusercontent.com/101700487/203040811-057ce151-1607-485d-a4b0-945be1339192.png"> | <img width="200" alt="스크린샷 2022-11-21 오후 8 33 02" src="https://user-images.githubusercontent.com/101700487/203043594-15526aab-30e3-47b6-a977-8e3747b7adb8.png"> |
|:---:|:---:|:---:|
```
