### ISSUE TITLE
[Design] 밴드상세의 타임라인 화면 UI를 구현합니다.

### ISSUE THREAD

**Issue by taehyeonk** [DeveloperAcademy-POSTECH/MacC-GetARock#70]
## 💡 Issue

밴드 상세 화면에서 타임라인 탭을 눌렀을 때 나와야 하는 화면 UI를 구현합니다.
<img src="https://user-images.githubusercontent.com/29690062/203049810-88c2c963-8f3e-4e53-ad68-5bf436578f82.png" width="300" height="">

## 📝  todo

- [ ] tableview로 타임라인 히스토리 출력
- [ ] tableview cell 구현
  - [ ] 이벤트 시작 시간, 이벤트 타이틀, 이벤트 상태
  - [ ] 좌측 히스토리 바(?)
